name: CI-CD pipeline PolyWard

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar validador HTML
        run: npm install -g html-validate

      - name: Validar HTML
        run: html-validate "*.html"

      - name: Busqueda de links rotos
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: '*.html'

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./